services:

  manager:
    build:
      context: ./crack-hash-manager/
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
    ports:
      - "${MANAGER_PORT}:${MANAGER_PORT}"
    env_file:
      .env
    networks:
      - crack_hash_net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:${MANAGER_PORT}/health || exit 1"]
      interval: 5s
      retries: 3
      timeout: 10s

  worker:
    build:
      context: ./crack-hash-worker/
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
    environment:
      MANAGER_ADDRESS: manager:${MANAGER_PORT}
      WORKER_GOROUTINE_COUNT: 10
      GOMAXPROCS: 10
      GOMEMLIMIT: 1GiB
    ports:
      - "6970:6970"
    networks:
      - crack_hash_net
    depends_on:
      manager:
        condition: service_healthy

networks:
  crack_hash_net:
    driver: bridge
    name: crack_hash
